name: Python Workflow

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main
      - develop
      - release/*

jobs:
  python-ci:
    runs-on: ubuntu-latest

    env:
      Name: "Кудрявцева Наталья Сергеевна"
      Group_Number: "М3112"

    steps:
      - name: Print user info
        run: |
          echo "Full_Name: ${{ env.Name }}"
          echo "Group_Number: ${{ env.Group_Number }}"
          echo "GitHub Username: ${{ github.actor }}"

      - name: Set up Python 3.13
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with unittest
        run: |
          python -m unittest discover -s tests

      - name: Check code style
        run: |
          pip install flake8
          flake8 .
